name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: snykctl
            asset_name: snykctl_linux-amd64
          - os: macos-latest
            artifact_name: snykctl
            asset_name: snykctl_darwin-amd64
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: MeilCli/setup-crystal-action@v3.0.0
      - name: Install dependencies
        run: shards install
      - name: Compile release
        run: |
          crystal -v
          crystal build src/compile.cr --release -o ${{ matrix.artifact_name }}
          chmod +x ${{ matrix.artifact_name }}
      - name: Add binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
